name: eslint check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: upload-dist-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Dist
        run: pnpm run lint
