name: lint

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    concurrency:
      group: eslint-check-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run Lint
        run: pnpm run lint
